import Config

config :baambook, BaambookWeb.Endpoint,
  http: [port: 4000],
  # secret_key_base: "P39HCa+/lO+T9MBd+dabhRiJfZe+uiNRXBa6kVbFhTVRtAu7DcnceqnrtUMcMRRA",
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    # Warning: directly execute mix task or use raw npm/node/etc
    # If running child elixir it will not exit at stdin EOF
    assets: {Mix.Task, :run, ["assets.watch"]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
# config :baambook, BaambookWeb.Endpoint,
#   live_reload: [
#     patterns: [
#       ~r"priv/static/.*$"
#     ]
#   ]

config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
